In [3]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [96]:
ds = pd.read_csv("data.csv")

In [7]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 25 columns):
 #   Column                           Non-Null Count   Dtype  
---  ------                           --------------   -----  
 0   No                               500000 non-null  int64  
 1   Property_Type                    500000 non-null  object 
 2   Land_Area                        500000 non-null  int64  
 3   Floor_Area                       500000 non-null  int64  
 4   Condition                        500000 non-null  object 
 5   View                             354981 non-null  object 
 6   Amenities                        419828 non-null  object 
 7   Furnishing_Status                460291 non-null  object 
 8   Air_Conditioning (Yes/No)        500000 non-null  object 
 9   Heating (Yes/No)                 500000 non-null  object 
 10  Kitchen_Type                     460291 non-null  object 
 11  Balcony (Yes/No)                 500000 non-null  object 
 12  Ma

In [13]:
ds.columns

Index(['No', 'Property_Type', 'Land_Area', 'Floor_Area', 'Condition', 'View',
       'Amenities', 'Furnishing_Status', 'Air_Conditioning (Yes/No)',
       'Heating (Yes/No)', 'Kitchen_Type', 'Balcony (Yes/No)',
       'Maintenance_Fees', 'Latitude', 'Longitude', 'Location',
       'Num_bathrooms', 'Num_rooms', 'Price',
       'distance to nearest MRT Station', 'distance to nearest Hospital',
       'distance to nearest School', 'distance to nearest Bus Stand',
       'distance to nearest Airport', 'Crimerate in area'],
      dtype='object')

In [19]:
for column in ds.columns:
    print("----------------------")
    print(column)
    print(ds[column].unique())

----------------------
No
[     1      2      3 ... 499998 499999 500000]
----------------------
Property_Type
['Condo' 'Farmhouse' 'Apartment' 'Villa' 'Penthouse' 'Bungalow' 'Land']
----------------------
Land_Area
[ 1784  1768  2667 ... 12246 15562 18217]
----------------------
Floor_Area
[1555 1530 2667 ... 9298 8970 9093]
----------------------
Condition
['New' 'Old' 'Renovated']
----------------------
View
[nan 'City View' 'Park Facing' 'Sea Facing']
----------------------
Amenities
['Basic' 'Rooftop Access' nan 'Parking' 'Parking, Gym'
 'Garden, Swimming Pool' 'Shared Gym' 'Parking, Garden, Swimming Pool'
 'Swimming Pool, Parking, Garden' 'Parking, Gym, Swimming Pool'
 'Garden, Swimming Pool, Gym' 'Garden, Gym' 'Garden, Parking'
 'Swimming Pool, Parking' 'Gym, Garden' 'Parking, Garden'
 'Gym, Swimming Pool' 'Swimming Pool, Parking, Gym'
 'Swimming Pool, Garden, Parking' 'Swimming Pool, Gym'
 'Gym, Garden, Parking' 'Swimming Pool, Gym, Parking'
 'Gym, Swimming Pool, Garden' 'Parki

In [23]:
#'View', 'Amenities', 'Furnishing_Status','Kitchen_Type'

In [98]:
ds["View"].unique()

array([nan, 'City View', 'Park Facing', 'Sea Facing'], dtype=object)

In [100]:
ds['View'].fillna('No View', inplace=True)

In [102]:
ds["Furnishing_Status"].unique()

array(['Fully Furnished', 'Semi Furnished', 'Unfurnished', nan],
      dtype=object)

In [104]:
ds[ds["Furnishing_Status"].isna()]["Property_Type"].unique()

array(['Land'], dtype=object)

In [106]:
ds['Furnishing_Status'].fillna('Not Needed', inplace=True)

In [108]:
ds["Kitchen_Type"].unique()

array(['Semi Modular', 'Normal', 'Modular', nan], dtype=object)

In [110]:
ds[ds["Kitchen_Type"].isna()]["Property_Type"].unique()

array(['Land'], dtype=object)

In [112]:
ds['Kitchen_Type'].fillna('Not Needed', inplace=True)

In [114]:
ds["Location"].unique()

array(['Phoenix', 'San Francisco', 'Miami', 'Chicago', 'New York',
       'Seattle', 'Los Angeles', 'Denver', 'Houston', 'Boston'],
      dtype=object)

In [116]:
ds["Amenities"].unique()

array(['Basic', 'Rooftop Access', nan, 'Parking', 'Parking, Gym',
       'Garden, Swimming Pool', 'Shared Gym',
       'Parking, Garden, Swimming Pool', 'Swimming Pool, Parking, Garden',
       'Parking, Gym, Swimming Pool', 'Garden, Swimming Pool, Gym',
       'Garden, Gym', 'Garden, Parking', 'Swimming Pool, Parking',
       'Gym, Garden', 'Parking, Garden', 'Gym, Swimming Pool',
       'Swimming Pool, Parking, Gym', 'Swimming Pool, Garden, Parking',
       'Swimming Pool, Gym', 'Gym, Garden, Parking',
       'Swimming Pool, Gym, Parking', 'Gym, Swimming Pool, Garden',
       'Parking, Swimming Pool, Gym', 'Gym, Parking, Swimming Pool',
       'Garden, Swimming Pool, Parking', 'Swimming Pool, Gym, Garden',
       'Gym, Parking', 'Parking, Garden, Gym',
       'Gym, Swimming Pool, Parking', 'Parking, Swimming Pool',
       'Swimming Pool, Garden, Gym', 'Garden, Gym, Parking',
       'Swimming Pool, Garden', 'Parking, Swimming Pool, Garden',
       'Gym, Parking, Garden', 'Garden, Park

In [118]:
ds['Amenities'].fillna('', inplace=True)

In [120]:
unique_amenities = set()
ds['Amenities'].dropna().str.split(',').apply(lambda x: unique_amenities.update(item.strip() for item in x if item.strip()))
# Convert set to list if needed
unique_amenities_list = list(unique_amenities)
print(unique_amenities_list)

['Parking', 'Shared Gym', 'Garden', 'Swimming Pool', 'Rooftop Access', 'Basic', 'Gym']


In [122]:
for amenity in unique_amenities_list:
    ds[amenity] = "No"

In [124]:
# for amenity in unique_amenities_list:
#     for i in ds.index:
#         if amenity in ds.loc[i, "Amenities"]:
#             ds.loc[i, amenity] = "Yes"
for amenity in unique_amenities_list:
    ds[amenity] = ds['Amenities'].apply(lambda x: 'Yes' if amenity in x else 'No')

In [130]:
ds = ds.drop('Amenities', axis=1)

In [134]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 31 columns):
 #   Column                           Non-Null Count   Dtype  
---  ------                           --------------   -----  
 0   No                               500000 non-null  int64  
 1   Property_Type                    500000 non-null  object 
 2   Land_Area                        500000 non-null  int64  
 3   Floor_Area                       500000 non-null  int64  
 4   Condition                        500000 non-null  object 
 5   View                             500000 non-null  object 
 6   Furnishing_Status                500000 non-null  object 
 7   Air_Conditioning (Yes/No)        500000 non-null  object 
 8   Heating (Yes/No)                 500000 non-null  object 
 9   Kitchen_Type                     500000 non-null  object 
 10  Balcony (Yes/No)                 500000 non-null  object 
 11  Maintenance_Fees                 500000 non-null  int64  
 12  La

In [136]:
ds.to_csv("cleaned_data.csv")